### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by rubenwo** [rubenwo/url-shortener#6]
Let's make a great url-shortener. Current version is working, but certainly not optimal (especially in the front-end)

In the spirit of hacktoberfest: Help wanted in: 

- securing api (preventing server overload and malicious links)
- front-end (it's very bare-bones at the moment)
- documentation (guide for deployments)
- faster / more reliable database implementations. Currently working with redis only.
- Deployments for various hosting services (k8s, heroku, etc.). docker-compose is supported at the moment. k8s is untested.

**Comment by thinkswell** [comment]
@rubenwo  Hey, I can help with the front end, you can assign me.

**Comment by rubenwo** [comment]
Closing issue since we now have a contributing.md file with the same information
