### ISSUE TITLE
API Rate limiting

### ISSUE THREAD

**Issue by tabarnhack** [rubenwo/url-shortener#9]
I'm interested in contributing to your project by looking at how to secure it, but I have some questions.

While reading your codebase, I see that you use [go-chi](https://github.com/go-chi/chi) for the HTTP router.

However, I also see that you reimplement a rate limiter by yourself although the maintainer of go-chi has already developed one. Is there any reason for that choice?

**Comment by rubenwo** [comment]
Great, glad to have the help.
As for the rate limiter, I must have overlooked that part of the documentation of go-chi :), but I see you're right.

Can I assign you to this issue?

**Comment by tabarnhack** [comment]
Of course!
